# This is a basic workflow to help you get started with Actions

name: Create Installer

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: What Properties version does this correspond to?
        required: true
      is-pre-release:
        type: boolean
        required: true
        description: "is this a prerelease version?"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "Setup\innosetup.iss"
      shell: cmd

    - name: Upload the installer as an artifact
      uses: actions/upload-artifact@v2      
      with:
        path: "Setup/Output/DahlDesignSetup.exe"
        name: wininstaller-innosetup
